//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminID { get; set; }
        public string admin_name { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
        public Nullable<int> teacherID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> systemID { get; set; }
        public Nullable<int> subjectID { get; set; }
        public Nullable<int> exam_bankID { get; set; }
        public Nullable<int> fileID { get; set; }
        public Nullable<int> notificationID { get; set; }
    
        public virtual exam_bank_management exam_bank_management { get; set; }
        public virtual file_management file_management { get; set; }
        public virtual notification_management notification_management { get; set; }
        public virtual subject_management subject_management { get; set; }
        public virtual system_management system_management { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual user_management user_management { get; set; }
    }
}
