//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library_03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_Library : DbContext
    {
        public E_Library()
            : base("name=E_Library")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<exam_and_test_management> exam_and_test_management { get; set; }
        public virtual DbSet<exam_bank_management> exam_bank_management { get; set; }
        public virtual DbSet<file_management> file_management { get; set; }
        public virtual DbSet<help_management> help_management { get; set; }
        public virtual DbSet<lession_management> lession_management { get; set; }
        public virtual DbSet<notification_management> notification_management { get; set; }
        public virtual DbSet<resource_management> resource_management { get; set; }
        public virtual DbSet<subject_management> subject_management { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<system_management> system_management { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<user_management> user_management { get; set; }
    }
}
