//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Library_03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher()
        {
            this.admins = new HashSet<admin>();
        }
    
        public int teacherID { get; set; }
        public string teacher_name { get; set; }
        public Nullable<int> subjectID { get; set; }
        public Nullable<int> lessionID { get; set; }
        public Nullable<int> resourceID { get; set; }
        public Nullable<int> exam_and_test_ID { get; set; }
        public Nullable<int> notificationID { get; set; }
        public Nullable<int> helpID { get; set; }
        public Nullable<int> userID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin> admins { get; set; }
        public virtual exam_and_test_management exam_and_test_management { get; set; }
        public virtual help_management help_management { get; set; }
        public virtual lession_management lession_management { get; set; }
        public virtual notification_management notification_management { get; set; }
        public virtual resource_management resource_management { get; set; }
        public virtual subject_management subject_management { get; set; }
        public virtual user_management user_management { get; set; }
    }
}
